# Generated by Django 3.0.1 on 2019-12-19 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myfavs', '0002_auto_20191219_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Versions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('v_number', models.IntegerField(default=None, verbose_name='バージョン番号')),
                ('v_title', models.CharField(default=None, max_length=200, verbose_name='バージョン名')),
            ],
        ),
        migrations.AlterField(
            model_name='music',
            name='version',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myfavs.Versions'),
        ),
    ]
