# Generated by Django 3.0.1 on 2019-12-19 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myfavs', '0003_auto_20191219_1549'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Versions',
            new_name='Version',
        ),
    ]
